AllCops:
  TargetRubyVersion: 2.7

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/SymbolProc:
  Exclude:
    - 'app/admin/**/*'

Style/MultilineIfModifier:
  Exclude:
    - 'app/admin/**/*'

Metrics/LineLength:
  Max: 120
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'
    - '**/*_helper.rb'
    - '**/*_preview.rb'

Metrics/AbcSize:
  Exclude:
    - '**/*_spec.rb'

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/MethodLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/*_helper.rb'

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - '**/factories/**.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
