default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres

development:
  <<: *default
  database: bullpen_development
  username: superuser
  password: password

test:
  <<: *default
  database: bullpen_test
  username: superuser
  password: password
staging:
  <<: *default
  database: bullpen_production
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>

production:
  <<: *default
  database: bullpen_production
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>

admin:
  database: bullpen_production
  username: <%= ENV['PRODUCTION_DATABASE_USERNAME'] %>
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
